name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run generate

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: Namet.ag JS Library
          path: ./client/namet.ag-*.tgz
          if-no-files-found: error