name: Build

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: true

      - name: Update OpenAPI spec
        run: |
          git config --global user.name "Namet.ag"
          git config --global user.email "nametag@eyezah.com"
          cd openapi
          git fetch origin
          git reset --hard origin/main
          cd ..

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run generate
      
      - name: Push changes
        run: |
          pwd
          git add .
          git commit -m "Update library"
          git push

      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: Namet.ag JS Library
          path: ./client/namet.ag-*.tgz
          if-no-files-found: error